#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

NAME=c2
SCRIPT="/opt/zator/extra_strats/c2.sh"

start_service() {
    [ -x "$SCRIPT" ] || { echo "$NAME: $SCRIPT не найден"; return 1; }
    procd_open_instance
    procd_set_param command "$SCRIPT"
    procd_set_param respawn
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_close_instance
}

stop_service() {
    killall tcpdump 2>/dev/null
}
